import test from 'node:test';
import assert from 'node:assert/strict';
import {XMLParser} from 'fast-xml-parser';
import {addDay,addPoint,dayStats,exportPlottedGpx,newDraft,preparePlottedPlan,updateDay,validateDraft} from '../src/lib/plotting.mjs';
import {cloudPayload} from '../src/lib/workspace.mjs';
function completed(){let d=newDraft(undefined,'2026-09-28');d=addPoint(d,0,{lat:57.412,lon:-6.191,name:'Launch & return'});return addPoint(d,0,{lat:57.412,lon:-6.181});}
test('manual plotting preserves exact chosen coordinates and never adds a route automatically',()=>{let d=newDraft();assert.deepEqual(d.days[0].points,[]);d=completed();assert.deepEqual(d.days[0].points.map(p=>[p.lat,p.lon]),[[57.412,-6.191],[57.412,-6.181]]);const moved=updateDay(d,0,{points:d.days[0].points.map((p,i)=>i?{...p,lon:-6.171}:p)});assert.ok(dayStats(moved.days[0]).distanceKm>dayStats(d.days[0]).distanceKm);const undo=updateDay(d,0,{points:d.days[0].points.slice(0,-1)});assert.equal(undo.days[0].points.length,1);assert.equal(d.days[0].points.length,2);assert.throws(()=>preparePlottedPlan(undo),/two points/);});
test('four-day GPX keeps transfers out of distance and exports separate, explicitly unvalidated tracks',()=>{let d=completed();for(let i=1;i<4;i++){d=addDay(d);d=addPoint(d,i,{lat:57.1+i*.05,lon:-6.3});d=addPoint(d,i,{lat:57.1+i*.05,lon:-6.29});}const plan=preparePlottedPlan(d);assert.ok(plan.totalDistanceKm<4);const xml=exportPlottedGpx(plan);const parsed=new XMLParser({ignoreAttributes:false}).parse(xml);assert.equal(parsed.gpx.trk.length,4);assert.equal(parsed.gpx.trk[0].trkseg.trkpt[0].name,'Launch & return');assert.match(parsed.gpx.metadata.desc,/not been validated/);assert.match(parsed.gpx.trk[3].name,/2026-10-01/);assert.equal(parsed.gpx.trk[0].trkseg.trkpt.length,2);});
test('empty days, impossible dates and out-of-bounds coordinates cannot be saved or exported',()=>{let d=addDay(completed());assert.throws(()=>exportPlottedGpx(d),/day 2/);assert.throws(()=>validateDraft({...completed(),startDate:'2026-02-30'}),/valid start date/);assert.throws(()=>addPoint(completed(),0,{lat:95,lon:0}),/point/);assert.throws(()=>validateDraft({...completed(),days:[{points:[null],stops:[],notes:''}]}));});
test('drafts, screenshots and session files never become background cloud writes',()=>{const p={profile:{name:'Alex'},plans:[],draft:completed(),photos:['private'],activities:['private']};assert.deepEqual(cloudPayload(p),{profile:{name:'Alex'},plans:[]});});
